---
- name: include common.yml
  include_tasks: common.yml

- name: include_tasks pre_requisite.yml
  include_tasks: pre_requisite.yml
  when: not containerized_deployment | bool

- name: rgw pool creation tasks
  include_tasks: rgw_create_pools.yml
  when: rgw_create_pools is defined

- name: include_tasks openstack-keystone.yml
  include_tasks: openstack-keystone.yml
  when: radosgw_keystone_ssl | bool

- name: include_tasks start_radosgw.yml
  include_tasks: start_radosgw.yml
  when: not containerized_deployment | bool

- name: include_tasks container/main.yml
  include_tasks: container/main.yml
  when: containerized_deployment | bool

- name: include_tasks multisite/main.yml
  include_tasks: multisite/main.yml
  when: rgw_multisite | bool
